// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Enums.proto

package com.focustech.tm.open.sdk.messages.protobuf;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Enable
      implements com.google.protobuf.ProtocolMessageEnum {
    DISABLE(0, 0),
    ENABLE(1, 1),
    ;
    
    public static final int DISABLE_VALUE = 0;
    public static final int ENABLE_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static Enable valueOf(int value) {
      switch (value) {
        case 0: return DISABLE;
        case 1: return ENABLE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Enable>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Enable>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Enable>() {
            public Enable findValueByNumber(int number) {
              return Enable.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Enable[] VALUES = {
      DISABLE, ENABLE, 
    };
    
    public static Enable valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Enable(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.Enable)
  }
  
  public enum Equipment
      implements com.google.protobuf.ProtocolMessageEnum {
    PC(0, 1),
    WEB(1, 2),
    MOBILE_IOS(2, 3),
    MOBILE_ANDROID(3, 4),
    ;
    
    public static final int PC_VALUE = 1;
    public static final int WEB_VALUE = 2;
    public static final int MOBILE_IOS_VALUE = 3;
    public static final int MOBILE_ANDROID_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static Equipment valueOf(int value) {
      switch (value) {
        case 1: return PC;
        case 2: return WEB;
        case 3: return MOBILE_IOS;
        case 4: return MOBILE_ANDROID;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Equipment>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Equipment>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Equipment>() {
            public Equipment findValueByNumber(int number) {
              return Equipment.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Equipment[] VALUES = {
      PC, WEB, MOBILE_IOS, MOBILE_ANDROID, 
    };
    
    public static Equipment valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Equipment(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.Equipment)
  }
  
  public enum HeadType
      implements com.google.protobuf.ProtocolMessageEnum {
    SYSTEM(0, 0),
    CUSTOM(1, 1),
    ;
    
    public static final int SYSTEM_VALUE = 0;
    public static final int CUSTOM_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static HeadType valueOf(int value) {
      switch (value) {
        case 0: return SYSTEM;
        case 1: return CUSTOM;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<HeadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HeadType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeadType>() {
            public HeadType findValueByNumber(int number) {
              return HeadType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(2);
    }
    
    private static final HeadType[] VALUES = {
      SYSTEM, CUSTOM, 
    };
    
    public static HeadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private HeadType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.HeadType)
  }
  
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    ONLINE(0, 1),
    LEAVE(1, 2),
    BUSY(2, 3),
    HIDE(3, 4),
    OFFLINE(4, 5),
    LOGIC_ONLINE(5, 6),
    ;
    
    public static final int ONLINE_VALUE = 1;
    public static final int LEAVE_VALUE = 2;
    public static final int BUSY_VALUE = 3;
    public static final int HIDE_VALUE = 4;
    public static final int OFFLINE_VALUE = 5;
    public static final int LOGIC_ONLINE_VALUE = 6;
    
    
    public final int getNumber() { return value; }
    
    public static Status valueOf(int value) {
      switch (value) {
        case 1: return ONLINE;
        case 2: return LEAVE;
        case 3: return BUSY;
        case 4: return HIDE;
        case 5: return OFFLINE;
        case 6: return LOGIC_ONLINE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(3);
    }
    
    private static final Status[] VALUES = {
      ONLINE, LEAVE, BUSY, HIDE, OFFLINE, LOGIC_ONLINE, 
    };
    
    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Status(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.Status)
  }
  
  public enum FriendGroupType
      implements com.google.protobuf.ProtocolMessageEnum {
    DEFAULT(0, 0),
    STRANGER(1, 1),
    BLACKLIST(2, 2),
    USER_CUSTOM(3, 3),
    ;
    
    public static final int DEFAULT_VALUE = 0;
    public static final int STRANGER_VALUE = 1;
    public static final int BLACKLIST_VALUE = 2;
    public static final int USER_CUSTOM_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static FriendGroupType valueOf(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return STRANGER;
        case 2: return BLACKLIST;
        case 3: return USER_CUSTOM;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<FriendGroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FriendGroupType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FriendGroupType>() {
            public FriendGroupType findValueByNumber(int number) {
              return FriendGroupType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(4);
    }
    
    private static final FriendGroupType[] VALUES = {
      DEFAULT, STRANGER, BLACKLIST, USER_CUSTOM, 
    };
    
    public static FriendGroupType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private FriendGroupType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.FriendGroupType)
  }
  
  public enum RecentContactType
      implements com.google.protobuf.ProtocolMessageEnum {
    PERSON(0, 0),
    GROUP(1, 1),
    DISCUSSION(2, 2),
    ;
    
    public static final int PERSON_VALUE = 0;
    public static final int GROUP_VALUE = 1;
    public static final int DISCUSSION_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static RecentContactType valueOf(int value) {
      switch (value) {
        case 0: return PERSON;
        case 1: return GROUP;
        case 2: return DISCUSSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RecentContactType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RecentContactType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RecentContactType>() {
            public RecentContactType findValueByNumber(int number) {
              return RecentContactType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(5);
    }
    
    private static final RecentContactType[] VALUES = {
      PERSON, GROUP, DISCUSSION, 
    };
    
    public static RecentContactType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RecentContactType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.RecentContactType)
  }
  
  public enum ValidateRule
      implements com.google.protobuf.ProtocolMessageEnum {
    ALLOW_WITHOUT_VALIDATE(0, 0),
    ALLOW_AFTER_VALIDATE(1, 1),
    DENY(2, 2),
    ;
    
    public static final int ALLOW_WITHOUT_VALIDATE_VALUE = 0;
    public static final int ALLOW_AFTER_VALIDATE_VALUE = 1;
    public static final int DENY_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static ValidateRule valueOf(int value) {
      switch (value) {
        case 0: return ALLOW_WITHOUT_VALIDATE;
        case 1: return ALLOW_AFTER_VALIDATE;
        case 2: return DENY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ValidateRule>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ValidateRule>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ValidateRule>() {
            public ValidateRule findValueByNumber(int number) {
              return ValidateRule.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(6);
    }
    
    private static final ValidateRule[] VALUES = {
      ALLOW_WITHOUT_VALIDATE, ALLOW_AFTER_VALIDATE, DENY, 
    };
    
    public static ValidateRule valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ValidateRule(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.ValidateRule)
  }
  
  public enum FriendAnswer
      implements com.google.protobuf.ProtocolMessageEnum {
    REFUSE(0, 0),
    AGREE(1, 1),
    AGREE_AND_ADD(2, 2),
    ;
    
    public static final int REFUSE_VALUE = 0;
    public static final int AGREE_VALUE = 1;
    public static final int AGREE_AND_ADD_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static FriendAnswer valueOf(int value) {
      switch (value) {
        case 0: return REFUSE;
        case 1: return AGREE;
        case 2: return AGREE_AND_ADD;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<FriendAnswer>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FriendAnswer>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FriendAnswer>() {
            public FriendAnswer findValueByNumber(int number) {
              return FriendAnswer.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(7);
    }
    
    private static final FriendAnswer[] VALUES = {
      REFUSE, AGREE, AGREE_AND_ADD, 
    };
    
    public static FriendAnswer valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private FriendAnswer(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.FriendAnswer)
  }
  
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    TEXT(0, 0),
    MULTI_MEDIA(1, 1),
    USER_ADD(2, 2),
    USER_QUIT(3, 3),
    INVITE_USER_JOIN(4, 4),
    AUTO_REPLY(5, 5),
    ;
    
    public static final int TEXT_VALUE = 0;
    public static final int MULTI_MEDIA_VALUE = 1;
    public static final int USER_ADD_VALUE = 2;
    public static final int USER_QUIT_VALUE = 3;
    public static final int INVITE_USER_JOIN_VALUE = 4;
    public static final int AUTO_REPLY_VALUE = 5;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return MULTI_MEDIA;
        case 2: return USER_ADD;
        case 3: return USER_QUIT;
        case 4: return INVITE_USER_JOIN;
        case 5: return AUTO_REPLY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(8);
    }
    
    private static final MessageType[] VALUES = {
      TEXT, MULTI_MEDIA, USER_ADD, USER_QUIT, INVITE_USER_JOIN, AUTO_REPLY, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.MessageType)
  }
  
  public enum MessageSense
      implements com.google.protobuf.ProtocolMessageEnum {
    MESSAGE(0, 0),
    GROUP_MESSAGE(1, 1),
    DISCUSSION_MESSAGE(2, 2),
    ;
    
    public static final int MESSAGE_VALUE = 0;
    public static final int GROUP_MESSAGE_VALUE = 1;
    public static final int DISCUSSION_MESSAGE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static MessageSense valueOf(int value) {
      switch (value) {
        case 0: return MESSAGE;
        case 1: return GROUP_MESSAGE;
        case 2: return DISCUSSION_MESSAGE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageSense>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageSense>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageSense>() {
            public MessageSense findValueByNumber(int number) {
              return MessageSense.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(9);
    }
    
    private static final MessageSense[] VALUES = {
      MESSAGE, GROUP_MESSAGE, DISCUSSION_MESSAGE, 
    };
    
    public static MessageSense valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageSense(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.MessageSense)
  }
  
  public enum ReceiveStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    FILE_SUCCESS(0, 0),
    FILE_REFUSE(1, 1),
    ;
    
    public static final int FILE_SUCCESS_VALUE = 0;
    public static final int FILE_REFUSE_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ReceiveStatus valueOf(int value) {
      switch (value) {
        case 0: return FILE_SUCCESS;
        case 1: return FILE_REFUSE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ReceiveStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ReceiveStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReceiveStatus>() {
            public ReceiveStatus findValueByNumber(int number) {
              return ReceiveStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(10);
    }
    
    private static final ReceiveStatus[] VALUES = {
      FILE_SUCCESS, FILE_REFUSE, 
    };
    
    public static ReceiveStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ReceiveStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.ReceiveStatus)
  }
  
  public enum GroupType
      implements com.google.protobuf.ProtocolMessageEnum {
    LEARNING_IS_LIMITLESS(0, 0),
    INNOVATION_WORKS(1, 1),
    ALL_SORTS_OF_GOSSIP(2, 2),
    USER_EXPERIENCE(3, 3),
    CASUAL_FASHION(4, 4),
    OTHER(5, 5),
    ;
    
    public static final int LEARNING_IS_LIMITLESS_VALUE = 0;
    public static final int INNOVATION_WORKS_VALUE = 1;
    public static final int ALL_SORTS_OF_GOSSIP_VALUE = 2;
    public static final int USER_EXPERIENCE_VALUE = 3;
    public static final int CASUAL_FASHION_VALUE = 4;
    public static final int OTHER_VALUE = 5;
    
    
    public final int getNumber() { return value; }
    
    public static GroupType valueOf(int value) {
      switch (value) {
        case 0: return LEARNING_IS_LIMITLESS;
        case 1: return INNOVATION_WORKS;
        case 2: return ALL_SORTS_OF_GOSSIP;
        case 3: return USER_EXPERIENCE;
        case 4: return CASUAL_FASHION;
        case 5: return OTHER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GroupType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GroupType>() {
            public GroupType findValueByNumber(int number) {
              return GroupType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(11);
    }
    
    private static final GroupType[] VALUES = {
      LEARNING_IS_LIMITLESS, INNOVATION_WORKS, ALL_SORTS_OF_GOSSIP, USER_EXPERIENCE, CASUAL_FASHION, OTHER, 
    };
    
    public static GroupType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private GroupType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.GroupType)
  }
  
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    NORMAL(0, 0),
    ADMIN(1, 1),
    OWNER(2, 2),
    ;
    
    public static final int NORMAL_VALUE = 0;
    public static final int ADMIN_VALUE = 1;
    public static final int OWNER_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static UserType valueOf(int value) {
      switch (value) {
        case 0: return NORMAL;
        case 1: return ADMIN;
        case 2: return OWNER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(12);
    }
    
    private static final UserType[] VALUES = {
      NORMAL, ADMIN, OWNER, 
    };
    
    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private UserType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.UserType)
  }
  
  public enum MessageSetting
      implements com.google.protobuf.ProtocolMessageEnum {
    ACCEPT_AND_PROMPT(0, 0),
    ACCEPT_NO_PROMPT(1, 1),
    REFUSE_MESSAGE(2, 2),
    ;
    
    public static final int ACCEPT_AND_PROMPT_VALUE = 0;
    public static final int ACCEPT_NO_PROMPT_VALUE = 1;
    public static final int REFUSE_MESSAGE_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static MessageSetting valueOf(int value) {
      switch (value) {
        case 0: return ACCEPT_AND_PROMPT;
        case 1: return ACCEPT_NO_PROMPT;
        case 2: return REFUSE_MESSAGE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageSetting>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageSetting>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageSetting>() {
            public MessageSetting findValueByNumber(int number) {
              return MessageSetting.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.getDescriptor().getEnumTypes().get(13);
    }
    
    private static final MessageSetting[] VALUES = {
      ACCEPT_AND_PROMPT, ACCEPT_NO_PROMPT, REFUSE_MESSAGE, 
    };
    
    public static MessageSetting valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageSetting(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.focustech.tm.open.sdk.messages.protobuf.MessageSetting)
  }
  
  public interface EquipmentStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.focustech.tm.open.sdk.messages.protobuf.Equipment equipment = 1 [default = PC];
    boolean hasEquipment();
    com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment getEquipment();
    
    // required .com.focustech.tm.open.sdk.messages.protobuf.Status status = 2;
    boolean hasStatus();
    com.focustech.tm.open.sdk.messages.protobuf.Enums.Status getStatus();
  }
  public static final class EquipmentStatus extends
      com.google.protobuf.GeneratedMessage
      implements EquipmentStatusOrBuilder {
    // Use EquipmentStatus.newBuilder() to construct.
    private EquipmentStatus(Builder builder) {
      super(builder);
    }
    private EquipmentStatus(boolean noInit) {}
    
    private static final EquipmentStatus defaultInstance;
    public static EquipmentStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public EquipmentStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .com.focustech.tm.open.sdk.messages.protobuf.Equipment equipment = 1 [default = PC];
    public static final int EQUIPMENT_FIELD_NUMBER = 1;
    private com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment equipment_;
    public boolean hasEquipment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment getEquipment() {
      return equipment_;
    }
    
    // required .com.focustech.tm.open.sdk.messages.protobuf.Status status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private com.focustech.tm.open.sdk.messages.protobuf.Enums.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.focustech.tm.open.sdk.messages.protobuf.Enums.Status getStatus() {
      return status_;
    }
    
    private void initFields() {
      equipment_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment.PC;
      status_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Status.ONLINE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, equipment_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, equipment_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_fieldAccessorTable;
      }
      
      // Construct using com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        equipment_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment.PC;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Status.ONLINE;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.getDescriptor();
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus getDefaultInstanceForType() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.getDefaultInstance();
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus build() {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus buildPartial() {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus result = new com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.equipment_ = equipment_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus) {
          return mergeFrom((com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus other) {
        if (other == com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.getDefaultInstance()) return this;
        if (other.hasEquipment()) {
          setEquipment(other.getEquipment());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment value = com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                equipment_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.focustech.tm.open.sdk.messages.protobuf.Enums.Status value = com.focustech.tm.open.sdk.messages.protobuf.Enums.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.focustech.tm.open.sdk.messages.protobuf.Equipment equipment = 1 [default = PC];
      private com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment equipment_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment.PC;
      public boolean hasEquipment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment getEquipment() {
        return equipment_;
      }
      public Builder setEquipment(com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        equipment_ = value;
        onChanged();
        return this;
      }
      public Builder clearEquipment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        equipment_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Equipment.PC;
        onChanged();
        return this;
      }
      
      // required .com.focustech.tm.open.sdk.messages.protobuf.Status status = 2;
      private com.focustech.tm.open.sdk.messages.protobuf.Enums.Status status_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Status.ONLINE;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.Status getStatus() {
        return status_;
      }
      public Builder setStatus(com.focustech.tm.open.sdk.messages.protobuf.Enums.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.focustech.tm.open.sdk.messages.protobuf.Enums.Status.ONLINE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.focustech.tm.open.sdk.messages.protobuf.EquipmentStatus)
    }
    
    static {
      defaultInstance = new EquipmentStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.focustech.tm.open.sdk.messages.protobuf.EquipmentStatus)
  }
  
  public interface FriendStatusRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string friendUserId = 1;
    boolean hasFriendUserId();
    String getFriendUserId();
    
    // repeated .com.focustech.tm.open.sdk.messages.protobuf.EquipmentStatus status = 2;
    java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> 
        getStatusList();
    com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus getStatus(int index);
    int getStatusCount();
    java.util.List<? extends com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder> 
        getStatusOrBuilderList();
    com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder getStatusOrBuilder(
        int index);
  }
  public static final class FriendStatusRsp extends
      com.google.protobuf.GeneratedMessage
      implements FriendStatusRspOrBuilder {
    // Use FriendStatusRsp.newBuilder() to construct.
    private FriendStatusRsp(Builder builder) {
      super(builder);
    }
    private FriendStatusRsp(boolean noInit) {}
    
    private static final FriendStatusRsp defaultInstance;
    public static FriendStatusRsp getDefaultInstance() {
      return defaultInstance;
    }
    
    public FriendStatusRsp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string friendUserId = 1;
    public static final int FRIENDUSERID_FIELD_NUMBER = 1;
    private java.lang.Object friendUserId_;
    public boolean hasFriendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFriendUserId() {
      java.lang.Object ref = friendUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          friendUserId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFriendUserIdBytes() {
      java.lang.Object ref = friendUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        friendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.focustech.tm.open.sdk.messages.protobuf.EquipmentStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> status_;
    public java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> getStatusList() {
      return status_;
    }
    public java.util.List<? extends com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder> 
        getStatusOrBuilderList() {
      return status_;
    }
    public int getStatusCount() {
      return status_.size();
    }
    public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus getStatus(int index) {
      return status_.get(index);
    }
    public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder getStatusOrBuilder(
        int index) {
      return status_.get(index);
    }
    
    private void initFields() {
      friendUserId_ = "";
      status_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFriendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStatusCount(); i++) {
        if (!getStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFriendUserIdBytes());
      }
      for (int i = 0; i < status_.size(); i++) {
        output.writeMessage(2, status_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFriendUserIdBytes());
      }
      for (int i = 0; i < status_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, status_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_fieldAccessorTable;
      }
      
      // Construct using com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        friendUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (statusBuilder_ == null) {
          status_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          statusBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.getDescriptor();
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp getDefaultInstanceForType() {
        return com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.getDefaultInstance();
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp build() {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp buildPartial() {
        com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp result = new com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friendUserId_ = friendUserId_;
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            status_ = java.util.Collections.unmodifiableList(status_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp) {
          return mergeFrom((com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp other) {
        if (other == com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.getDefaultInstance()) return this;
        if (other.hasFriendUserId()) {
          setFriendUserId(other.getFriendUserId());
        }
        if (statusBuilder_ == null) {
          if (!other.status_.isEmpty()) {
            if (status_.isEmpty()) {
              status_ = other.status_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStatusIsMutable();
              status_.addAll(other.status_);
            }
            onChanged();
          }
        } else {
          if (!other.status_.isEmpty()) {
            if (statusBuilder_.isEmpty()) {
              statusBuilder_.dispose();
              statusBuilder_ = null;
              status_ = other.status_;
              bitField0_ = (bitField0_ & ~0x00000002);
              statusBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStatusFieldBuilder() : null;
            } else {
              statusBuilder_.addAllMessages(other.status_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFriendUserId()) {
          
          return false;
        }
        for (int i = 0; i < getStatusCount(); i++) {
          if (!getStatus(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              friendUserId_ = input.readBytes();
              break;
            }
            case 18: {
              com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder subBuilder = com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStatus(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string friendUserId = 1;
      private java.lang.Object friendUserId_ = "";
      public boolean hasFriendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFriendUserId() {
        java.lang.Object ref = friendUserId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          friendUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFriendUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        friendUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friendUserId_ = getDefaultInstance().getFriendUserId();
        onChanged();
        return this;
      }
      void setFriendUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        friendUserId_ = value;
        onChanged();
      }
      
      // repeated .com.focustech.tm.open.sdk.messages.protobuf.EquipmentStatus status = 2;
      private java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> status_ =
        java.util.Collections.emptyList();
      private void ensureStatusIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          status_ = new java.util.ArrayList<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus>(status_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder> statusBuilder_;
      
      public java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> getStatusList() {
        if (statusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(status_);
        } else {
          return statusBuilder_.getMessageList();
        }
      }
      public int getStatusCount() {
        if (statusBuilder_ == null) {
          return status_.size();
        } else {
          return statusBuilder_.getCount();
        }
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus getStatus(int index) {
        if (statusBuilder_ == null) {
          return status_.get(index);
        } else {
          return statusBuilder_.getMessage(index);
        }
      }
      public Builder setStatus(
          int index, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusIsMutable();
          status_.set(index, value);
          onChanged();
        } else {
          statusBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setStatus(
          int index, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder builderForValue) {
        if (statusBuilder_ == null) {
          ensureStatusIsMutable();
          status_.set(index, builderForValue.build());
          onChanged();
        } else {
          statusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addStatus(com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusIsMutable();
          status_.add(value);
          onChanged();
        } else {
          statusBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addStatus(
          int index, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatusIsMutable();
          status_.add(index, value);
          onChanged();
        } else {
          statusBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addStatus(
          com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder builderForValue) {
        if (statusBuilder_ == null) {
          ensureStatusIsMutable();
          status_.add(builderForValue.build());
          onChanged();
        } else {
          statusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addStatus(
          int index, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder builderForValue) {
        if (statusBuilder_ == null) {
          ensureStatusIsMutable();
          status_.add(index, builderForValue.build());
          onChanged();
        } else {
          statusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllStatus(
          java.lang.Iterable<? extends com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus> values) {
        if (statusBuilder_ == null) {
          ensureStatusIsMutable();
          super.addAll(values, status_);
          onChanged();
        } else {
          statusBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        return this;
      }
      public Builder removeStatus(int index) {
        if (statusBuilder_ == null) {
          ensureStatusIsMutable();
          status_.remove(index);
          onChanged();
        } else {
          statusBuilder_.remove(index);
        }
        return this;
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder getStatusBuilder(
          int index) {
        return getStatusFieldBuilder().getBuilder(index);
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder getStatusOrBuilder(
          int index) {
        if (statusBuilder_ == null) {
          return status_.get(index);  } else {
          return statusBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder> 
           getStatusOrBuilderList() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(status_);
        }
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder addStatusBuilder() {
        return getStatusFieldBuilder().addBuilder(
            com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.getDefaultInstance());
      }
      public com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder addStatusBuilder(
          int index) {
        return getStatusFieldBuilder().addBuilder(
            index, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.getDefaultInstance());
      }
      public java.util.List<com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder> 
           getStatusBuilderList() {
        return getStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder, com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatusOrBuilder>(
                  status_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.focustech.tm.open.sdk.messages.protobuf.FriendStatusRsp)
    }
    
    static {
      defaultInstance = new FriendStatusRsp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.focustech.tm.open.sdk.messages.protobuf.FriendStatusRsp)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/Enums.proto\022+com.focustech.tm.op" +
      "en.sdk.messages.protobuf\"\245\001\n\017EquipmentSt" +
      "atus\022M\n\tequipment\030\001 \001(\01626.com.focustech." +
      "tm.open.sdk.messages.protobuf.Equipment:" +
      "\002PC\022C\n\006status\030\002 \002(\01623.com.focustech.tm.o" +
      "pen.sdk.messages.protobuf.Status\"u\n\017Frie" +
      "ndStatusRsp\022\024\n\014friendUserId\030\001 \002(\t\022L\n\006sta" +
      "tus\030\002 \003(\0132<.com.focustech.tm.open.sdk.me" +
      "ssages.protobuf.EquipmentStatus*!\n\006Enabl" +
      "e\022\013\n\007DISABLE\020\000\022\n\n\006ENABLE\020\001*@\n\tEquipment\022",
      "\006\n\002PC\020\001\022\007\n\003WEB\020\002\022\016\n\nMOBILE_IOS\020\003\022\022\n\016MOBI" +
      "LE_ANDROID\020\004*\"\n\010HeadType\022\n\n\006SYSTEM\020\000\022\n\n\006" +
      "CUSTOM\020\001*R\n\006Status\022\n\n\006ONLINE\020\001\022\t\n\005LEAVE\020" +
      "\002\022\010\n\004BUSY\020\003\022\010\n\004HIDE\020\004\022\013\n\007OFFLINE\020\005\022\020\n\014LO" +
      "GIC_ONLINE\020\006*L\n\017FriendGroupType\022\013\n\007DEFAU" +
      "LT\020\000\022\014\n\010STRANGER\020\001\022\r\n\tBLACKLIST\020\002\022\017\n\013USE" +
      "R_CUSTOM\020\003*:\n\021RecentContactType\022\n\n\006PERSO" +
      "N\020\000\022\t\n\005GROUP\020\001\022\016\n\nDISCUSSION\020\002*N\n\014Valida" +
      "teRule\022\032\n\026ALLOW_WITHOUT_VALIDATE\020\000\022\030\n\024AL" +
      "LOW_AFTER_VALIDATE\020\001\022\010\n\004DENY\020\002*8\n\014Friend",
      "Answer\022\n\n\006REFUSE\020\000\022\t\n\005AGREE\020\001\022\021\n\rAGREE_A" +
      "ND_ADD\020\002*k\n\013MessageType\022\010\n\004TEXT\020\000\022\017\n\013MUL" +
      "TI_MEDIA\020\001\022\014\n\010USER_ADD\020\002\022\r\n\tUSER_QUIT\020\003\022" +
      "\024\n\020INVITE_USER_JOIN\020\004\022\016\n\nAUTO_REPLY\020\005*F\n" +
      "\014MessageSense\022\013\n\007MESSAGE\020\000\022\021\n\rGROUP_MESS" +
      "AGE\020\001\022\026\n\022DISCUSSION_MESSAGE\020\002*2\n\rReceive" +
      "Status\022\020\n\014FILE_SUCCESS\020\000\022\017\n\013FILE_REFUSE\020" +
      "\001*\211\001\n\tGroupType\022\031\n\025LEARNING_IS_LIMITLESS" +
      "\020\000\022\024\n\020INNOVATION_WORKS\020\001\022\027\n\023ALL_SORTS_OF" +
      "_GOSSIP\020\002\022\023\n\017USER_EXPERIENCE\020\003\022\022\n\016CASUAL",
      "_FASHION\020\004\022\t\n\005OTHER\020\005*,\n\010UserType\022\n\n\006NOR" +
      "MAL\020\000\022\t\n\005ADMIN\020\001\022\t\n\005OWNER\020\002*Q\n\016MessageSe" +
      "tting\022\025\n\021ACCEPT_AND_PROMPT\020\000\022\024\n\020ACCEPT_N" +
      "O_PROMPT\020\001\022\022\n\016REFUSE_MESSAGE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_focustech_tm_open_sdk_messages_protobuf_EquipmentStatus_descriptor,
              new java.lang.String[] { "Equipment", "Status", },
              com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.class,
              com.focustech.tm.open.sdk.messages.protobuf.Enums.EquipmentStatus.Builder.class);
          internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_focustech_tm_open_sdk_messages_protobuf_FriendStatusRsp_descriptor,
              new java.lang.String[] { "FriendUserId", "Status", },
              com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.class,
              com.focustech.tm.open.sdk.messages.protobuf.Enums.FriendStatusRsp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
