// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: Head.proto

package com.focustech.tm.open.sdk.messages.protobuf;

public final class Head {
    private Head() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface TMHeadMessageOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // required string domainName = 1;
        boolean hasDomainName();

        String getDomainName();

        // required string cmd = 2;
        boolean hasCmd();

        String getCmd();

        // required string version = 3;
        boolean hasVersion();

        String getVersion();

        // required uint32 cliSeqId = 4;
        boolean hasCliSeqId();

        int getCliSeqId();

        // optional string svrSeqId = 5;
        boolean hasSvrSeqId();

        String getSvrSeqId();

        // optional string channelId = 6;
        boolean hasChannelId();

        String getChannelId();

        // optional string clientIp = 7;
        boolean hasClientIp();

        String getClientIp();
    }
    public static final class TMHeadMessage extends com.google.protobuf.GeneratedMessage implements
            TMHeadMessageOrBuilder {
        // Use TMHeadMessage.newBuilder() to construct.
        private TMHeadMessage(Builder builder) {
            super(builder);
        }

        private TMHeadMessage(boolean noInit) {
        }

        private static final TMHeadMessage defaultInstance;

        public static TMHeadMessage getDefaultInstance() {
            return defaultInstance;
        }

        public TMHeadMessage getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.focustech.tm.open.sdk.messages.protobuf.Head.internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.focustech.tm.open.sdk.messages.protobuf.Head.internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_fieldAccessorTable;
        }

        private int bitField0_;
        // required string domainName = 1;
        public static final int DOMAINNAME_FIELD_NUMBER = 1;
        private java.lang.Object domainName_;

        public boolean hasDomainName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getDomainName() {
            java.lang.Object ref = domainName_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    domainName_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getDomainNameBytes() {
            java.lang.Object ref = domainName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                domainName_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string cmd = 2;
        public static final int CMD_FIELD_NUMBER = 2;
        private java.lang.Object cmd_;

        public boolean hasCmd() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getCmd() {
            java.lang.Object ref = cmd_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    cmd_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getCmdBytes() {
            java.lang.Object ref = cmd_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                cmd_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string version = 3;
        public static final int VERSION_FIELD_NUMBER = 3;
        private java.lang.Object version_;

        public boolean hasVersion() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public String getVersion() {
            java.lang.Object ref = version_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    version_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getVersionBytes() {
            java.lang.Object ref = version_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                version_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required uint32 cliSeqId = 4;
        public static final int CLISEQID_FIELD_NUMBER = 4;
        private int cliSeqId_;

        public boolean hasCliSeqId() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getCliSeqId() {
            return cliSeqId_;
        }

        // optional string svrSeqId = 5;
        public static final int SVRSEQID_FIELD_NUMBER = 5;
        private java.lang.Object svrSeqId_;

        public boolean hasSvrSeqId() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public String getSvrSeqId() {
            java.lang.Object ref = svrSeqId_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    svrSeqId_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getSvrSeqIdBytes() {
            java.lang.Object ref = svrSeqId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                svrSeqId_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string channelId = 6;
        public static final int CHANNELID_FIELD_NUMBER = 6;
        private java.lang.Object channelId_;

        public boolean hasChannelId() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public String getChannelId() {
            java.lang.Object ref = channelId_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    channelId_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getChannelIdBytes() {
            java.lang.Object ref = channelId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                channelId_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string clientIp = 7;
        public static final int CLIENTIP_FIELD_NUMBER = 7;
        private java.lang.Object clientIp_;

        public boolean hasClientIp() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        public String getClientIp() {
            java.lang.Object ref = clientIp_;
            if (ref instanceof String) {
                return (String) ref;
            }
            else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    clientIp_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getClientIpBytes() {
            java.lang.Object ref = clientIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                clientIp_ = b;
                return b;
            }
            else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            domainName_ = "";
            cmd_ = "";
            version_ = "";
            cliSeqId_ = 0;
            svrSeqId_ = "";
            channelId_ = "";
            clientIp_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasDomainName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCmd()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasVersion()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCliSeqId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getDomainNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getCmdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getVersionBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeUInt32(4, cliSeqId_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getSvrSeqIdBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBytes(6, getChannelIdBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBytes(7, getClientIpBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getDomainNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getCmdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getVersionBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream.computeUInt32Size(4, cliSeqId_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(5, getSvrSeqIdBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, getChannelIdBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(7, getClientIpBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(
                com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(
                com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseDelimitedFrom(
                java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            }
            else {
                return null;
            }
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage parseFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.focustech.tm.open.sdk.messages.protobuf.Head.internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.focustech.tm.open.sdk.messages.protobuf.Head.internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_fieldAccessorTable;
            }

            // Construct using com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                domainName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                cmd_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                version_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                cliSeqId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                svrSeqId_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                channelId_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                clientIp_ = "";
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.getDescriptor();
            }

            public com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage getDefaultInstanceForType() {
                return com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.getDefaultInstance();
            }

            public com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage build() {
                com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage buildPartial() {
                com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage result =
                        new com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.domainName_ = domainName_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.cmd_ = cmd_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.version_ = version_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.cliSeqId_ = cliSeqId_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.svrSeqId_ = svrSeqId_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.channelId_ = channelId_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.clientIp_ = clientIp_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage) {
                    return mergeFrom((com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage) other);
                }
                else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage other) {
                if (other == com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.getDefaultInstance())
                    return this;
                if (other.hasDomainName()) {
                    setDomainName(other.getDomainName());
                }
                if (other.hasCmd()) {
                    setCmd(other.getCmd());
                }
                if (other.hasVersion()) {
                    setVersion(other.getVersion());
                }
                if (other.hasCliSeqId()) {
                    setCliSeqId(other.getCliSeqId());
                }
                if (other.hasSvrSeqId()) {
                    setSvrSeqId(other.getSvrSeqId());
                }
                if (other.hasChannelId()) {
                    setChannelId(other.getChannelId());
                }
                if (other.hasClientIp()) {
                    setClientIp(other.getClientIp());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasDomainName()) {

                    return false;
                }
                if (!hasCmd()) {

                    return false;
                }
                if (!hasVersion()) {

                    return false;
                }
                if (!hasCliSeqId()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0 :
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default : {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10 : {
                            bitField0_ |= 0x00000001;
                            domainName_ = input.readBytes();
                            break;
                        }
                        case 18 : {
                            bitField0_ |= 0x00000002;
                            cmd_ = input.readBytes();
                            break;
                        }
                        case 26 : {
                            bitField0_ |= 0x00000004;
                            version_ = input.readBytes();
                            break;
                        }
                        case 32 : {
                            bitField0_ |= 0x00000008;
                            cliSeqId_ = input.readUInt32();
                            break;
                        }
                        case 42 : {
                            bitField0_ |= 0x00000010;
                            svrSeqId_ = input.readBytes();
                            break;
                        }
                        case 50 : {
                            bitField0_ |= 0x00000020;
                            channelId_ = input.readBytes();
                            break;
                        }
                        case 58 : {
                            bitField0_ |= 0x00000040;
                            clientIp_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string domainName = 1;
            private java.lang.Object domainName_ = "";

            public boolean hasDomainName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getDomainName() {
                java.lang.Object ref = domainName_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    domainName_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setDomainName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                domainName_ = value;
                onChanged();
                return this;
            }

            public Builder clearDomainName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                domainName_ = getDefaultInstance().getDomainName();
                onChanged();
                return this;
            }

            void setDomainName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                domainName_ = value;
                onChanged();
            }

            // required string cmd = 2;
            private java.lang.Object cmd_ = "";

            public boolean hasCmd() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getCmd() {
                java.lang.Object ref = cmd_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    cmd_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setCmd(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                cmd_ = value;
                onChanged();
                return this;
            }

            public Builder clearCmd() {
                bitField0_ = (bitField0_ & ~0x00000002);
                cmd_ = getDefaultInstance().getCmd();
                onChanged();
                return this;
            }

            void setCmd(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                cmd_ = value;
                onChanged();
            }

            // required string version = 3;
            private java.lang.Object version_ = "";

            public boolean hasVersion() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public String getVersion() {
                java.lang.Object ref = version_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    version_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setVersion(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                version_ = value;
                onChanged();
                return this;
            }

            public Builder clearVersion() {
                bitField0_ = (bitField0_ & ~0x00000004);
                version_ = getDefaultInstance().getVersion();
                onChanged();
                return this;
            }

            void setVersion(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000004;
                version_ = value;
                onChanged();
            }

            // required uint32 cliSeqId = 4;
            private int cliSeqId_;

            public boolean hasCliSeqId() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getCliSeqId() {
                return cliSeqId_;
            }

            public Builder setCliSeqId(int value) {
                bitField0_ |= 0x00000008;
                cliSeqId_ = value;
                onChanged();
                return this;
            }

            public Builder clearCliSeqId() {
                bitField0_ = (bitField0_ & ~0x00000008);
                cliSeqId_ = 0;
                onChanged();
                return this;
            }

            // optional string svrSeqId = 5;
            private java.lang.Object svrSeqId_ = "";

            public boolean hasSvrSeqId() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public String getSvrSeqId() {
                java.lang.Object ref = svrSeqId_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    svrSeqId_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setSvrSeqId(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                svrSeqId_ = value;
                onChanged();
                return this;
            }

            public Builder clearSvrSeqId() {
                bitField0_ = (bitField0_ & ~0x00000010);
                svrSeqId_ = getDefaultInstance().getSvrSeqId();
                onChanged();
                return this;
            }

            void setSvrSeqId(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000010;
                svrSeqId_ = value;
                onChanged();
            }

            // optional string channelId = 6;
            private java.lang.Object channelId_ = "";

            public boolean hasChannelId() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public String getChannelId() {
                java.lang.Object ref = channelId_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    channelId_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setChannelId(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                channelId_ = value;
                onChanged();
                return this;
            }

            public Builder clearChannelId() {
                bitField0_ = (bitField0_ & ~0x00000020);
                channelId_ = getDefaultInstance().getChannelId();
                onChanged();
                return this;
            }

            void setChannelId(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000020;
                channelId_ = value;
                onChanged();
            }

            // optional string clientIp = 7;
            private java.lang.Object clientIp_ = "";

            public boolean hasClientIp() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public String getClientIp() {
                java.lang.Object ref = clientIp_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    clientIp_ = s;
                    return s;
                }
                else {
                    return (String) ref;
                }
            }

            public Builder setClientIp(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                clientIp_ = value;
                onChanged();
                return this;
            }

            public Builder clearClientIp() {
                bitField0_ = (bitField0_ & ~0x00000040);
                clientIp_ = getDefaultInstance().getClientIp();
                onChanged();
                return this;
            }

            void setClientIp(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000040;
                clientIp_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:com.focustech.tm.open.sdk.messages.protobuf.TMHeadMessage)
        }

        static {
            defaultInstance = new TMHeadMessage(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.focustech.tm.open.sdk.messages.protobuf.TMHeadMessage)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData =
                {"\n\nHead.proto\022+com.focustech.tm.open.sdk."
                        + "messages.protobuf\"\212\001\n\rTMHeadMessage\022\022\n\nd"
                        + "omainName\030\001 \002(\t\022\013\n\003cmd\030\002 \002(\t\022\017\n\007version\030"
                        + "\003 \002(\t\022\020\n\010cliSeqId\030\004 \002(\r\022\020\n\010svrSeqId\030\005 \001("
                        + "\t\022\021\n\tchannelId\030\006 \001(\t\022\020\n\010clientIp\030\007 \001(\t"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_fieldAccessorTable =
                                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                        internal_static_com_focustech_tm_open_sdk_messages_protobuf_TMHeadMessage_descriptor,
                                        new java.lang.String[]{"DomainName", "Cmd", "Version", "CliSeqId", "SvrSeqId",
                                                "ChannelId", "ClientIp",},
                                        com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.class,
                                        com.focustech.tm.open.sdk.messages.protobuf.Head.TMHeadMessage.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
